entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

api:
  dashboard: true

providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@example.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
