groups:
  - name: transcendence-general
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: 'Target down: {{ $labels.instance }}'
          description: 'The instance {{ $labels.instance }} is unreachable.'

      - alert: HighErrorRateBackend
        expr: rate(http_requests_total{job="backend",status=~"5.."}[5m]) / rate(http_requests_total{job="backend"}[5m]) > 0.05
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: 'High 5xx rate on backend'
          description: 'More than 5% of backend requests are failing.'

      - alert: HighContainerCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: 'High CPU usage'
          description: 'Container CPU usage over 85% for 10m.'
